version: '3.7'

services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"

  test-database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: api_simmr_test
      POSTGRES_PASSWORD: password
      POSTGRES_DB: api.simmr.test
    ports:
      - "6000:5432"

  # server:
  #   depends_on:
  #     - database
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   volumes:
  #     - ./:/app
  #   container_name: api-simmr
  #   expose:
  #     - '${API_PORT}'
  #   ports:
  #     - '${API_PORT}:${API_PORT}'
  #   command: yarn start:dev
