version: '3.7'

services:
  user:
    build:
      context: .
      dockerfile: ./user/Dockerfile
      target: dev
    volumes:
      - ./user:/app/user
    container_name: api-simmr-user
    expose:
      - '${USER_API_PORT}'
    ports:
      - '${USER_API_PORT}:${USER_API_PORT}'
    command: yarn dev

  space:
    build:
      context: .
      dockerfile: ./space/Dockerfile
      target: dev
    volumes:
      - ./space:/app/space
    container_name: api-simmr-space
    expose:
      - '${SPACE_API_PORT}'
    ports:
      - '${SPACE_API_PORT}:${SPACE_API_PORT}'
    command: yarn dev

  item:
    build:
      context: .
      dockerfile: ./item/Dockerfile
      target: dev
    volumes:
      - ./item:/app/item
    container_name: api-simmr-item
    expose:
      - '${ITEM_API_PORT}'
    ports:
      - '${ITEM_API_PORT}:${ITEM_API_PORT}'
    command: yarn dev